### PR TITLE
Remove visibility check before update

### LINKED ISSUE #196: swaggerhub api:update - Error: TOKEN_TYPE_INVALID
We are seeing issue in the swagger hub-cli while only updating the existing API . Creating and validation are working fine . 

### Q&A (please complete the following information)
 - CLI version: [e.g. 1.0.0] swaggerhub -v
swaggerhub-cli/0.3.0 win32-x64 node-v12.16.0
 -
 - OS: windows 10 enterprise 
 - Node.js version: node -v    ---- v12.16.0
 - SwaggerHub version if On-Premise: 1.23

### Describe the bug you're encountering
We are seeing issue while only updating the existing API . Creating and validation are working fine . 
 »   Error: TOKEN_TYPE_INVALID

### To reproduce...
1. Given adding the following in .bat file 
   -----
   @echo off
set SWAGGERHUB_URL=https://swaggerhubglobal.******.com/v1
set API_KEY=<api_key.txt
set NODE_EXTRA_CA_CERTS=swg.pem
Rem certutil.exe -addstore -f "TrustedPublisher" swg.pem
set "file=api.yaml"
for /f "tokens=* delims=: " %%i in ('FINDSTR /C:"version: " %file%') do set "version=%%i"
Rem echo %version%
set version_t=%version:~9%
set version_f=%version_t:~1,-1%
Rem echo %version_f%
for /f "tokens=* delims=: " %%j in ('FINDSTR /C:"title: " %file%') do set "title=%%j"
Rem echo %title:~7%
set title=%title: =-%
echo "updating the API..!!"
call swaggerhub api:update ***_Org/%title:~7%/%version_f%  --file=api.yaml --visibility=public
echo Creating API
call swaggerhub api:create ****_Org/%title:~7%/%version_f%  --file api.yaml --visibility public
echo "Validating the API.....!!!!"
call swaggerhub api:validate ****_Org/%title:~7%/%version_f%
------
2. Execute command - run the .bat file .
3. See error: 
C:\*****\swagger-cli\swagger\swagger>validate.bat
"updating the API..!!"
 »   Error: TOKEN_TYPE_INVALID
Creating API
 »   Error: API version '*****_Org/Inventory-BAPI-1234/1.0.7' already exists in SwaggerHub
"Validating the API.....!!!!"

### PR DESCRIPTION
**Pull request by barryadk**
The API visibility endpoint was exposed on the public SwaggerHub API (accessible via API key) in the SwaggerHub on-premise 1.26. (`/apis/{owner}/{api}/{version}/settings/private`)

To support previous versions of SwaggerHub on-premise we can change the API check in `api:update` to fetch the API version rather than its visibility flag.

Previously the `isPrivate` query parameter was always sent when POSTing the update, using the current API's setting when the visibility flag is not passed. The query parameter is only required when changing the visibility so we do not need to fetch the current value.

This will only resolve the case where the API definition is being updated. If the `file` argument is not used then the visibility update endpoint is required and will fail on On-premise versions older than 1.26

Closes #196

### CODE REVIEW

File: src/commands/api/update.js [hunk 1]
```diff
@@ -9,11 +9,18 @@ const { getResponseContent } = require('../../support/command/handle-response')
...
-  async updateApi({ owner, name, version, flags, isPrivate, visibility }) {
+  async updateApi(owner, name, version, flags) {
+    const queryParams = { version }
 
+    if (flags.visibility) {
+      queryParams['isPrivate'] = flags.visibility !== 'public'
+      this.logCommandSuccess = this.setSuccessMessage('ApiUpdateVisibility')
+    }
+
+    const visibility = queryParams['isPrivate'] ? 'private' : 'public'
```
Comment (conor-ward) [inline src/commands/api/update.js:20]: Can we just pass `visibility: flags.visibility` to the `logCommandSuccess` instead of doing this? 
Visibility only used if it isn't undefined anyway.

**Review by conor-ward — APPROVED** [review]

File: src/commands/api/update.js [hunk 2]
```diff
@@ -5,21 +5,26 @@ const { getApiIdentifierArg, splitPathParams } = require('../../support/command/
...
+
+    if (flags.visibility) {
+      queryParams['isPrivate'] = flags.visibility !== 'public'
+      this.logCommandSuccess = this.setSuccessMessage('ApiUpdateVisibility')
+    }
 
     const updateApiObj = {
       pathParams: [owner, name],
-      queryParams: { version, isPrivate },
+      queryParams: queryParams,
```
Comment (ben-smartbear) [inline src/commands/api/update.js:21]:
```suggestion
      queryParams,
```
es6 baby!

**Review by ben-smartbear — DISMISSED** [review]
looks good, we should just embrace our inner code golfer!

**Review by ben-smartbear — APPROVED** [review]
